/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SmartMapRouteImport } from './routes/smart-map'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as HazopRouteImport } from './routes/hazop'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as IndexRouteImport } from './routes/index'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartMapRoute = SmartMapRouteImport.update({
  id: '/smart-map',
  path: '/smart-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const HazopRoute = HazopRouteImport.update({
  id: '/hazop',
  path: '/hazop',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRoute
  '/exports': typeof ExportsRoute
  '/hazop': typeof HazopRoute
  '/inspector': typeof InspectorRoute
  '/inventory': typeof InventoryRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/smart-map': typeof SmartMapRoute
  '/upload': typeof UploadRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRoute
  '/exports': typeof ExportsRoute
  '/hazop': typeof HazopRoute
  '/inspector': typeof InspectorRoute
  '/inventory': typeof InventoryRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/smart-map': typeof SmartMapRoute
  '/upload': typeof UploadRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRoute
  '/exports': typeof ExportsRoute
  '/hazop': typeof HazopRoute
  '/inspector': typeof InspectorRoute
  '/inventory': typeof InventoryRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/smart-map': typeof SmartMapRoute
  '/upload': typeof UploadRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equipment'
    | '/exports'
    | '/hazop'
    | '/inspector'
    | '/inventory'
    | '/search'
    | '/settings'
    | '/smart-map'
    | '/upload'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/equipment'
    | '/exports'
    | '/hazop'
    | '/inspector'
    | '/inventory'
    | '/search'
    | '/settings'
    | '/smart-map'
    | '/upload'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/equipment'
    | '/exports'
    | '/hazop'
    | '/inspector'
    | '/inventory'
    | '/search'
    | '/settings'
    | '/smart-map'
    | '/upload'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipmentRoute: typeof EquipmentRoute
  ExportsRoute: typeof ExportsRoute
  HazopRoute: typeof HazopRoute
  InspectorRoute: typeof InspectorRoute
  InventoryRoute: typeof InventoryRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SmartMapRoute: typeof SmartMapRoute
  UploadRoute: typeof UploadRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-map': {
      id: '/smart-map'
      path: '/smart-map'
      fullPath: '/smart-map'
      preLoaderRoute: typeof SmartMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hazop': {
      id: '/hazop'
      path: '/hazop'
      fullPath: '/hazop'
      preLoaderRoute: typeof HazopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipmentRoute: EquipmentRoute,
  ExportsRoute: ExportsRoute,
  HazopRoute: HazopRoute,
  InspectorRoute: InspectorRoute,
  InventoryRoute: InventoryRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SmartMapRoute: SmartMapRoute,
  UploadRoute: UploadRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
